name: Python package
on: [push]
jobs:
   build:
       runs-on: ubuntu-16.04
       steps:
          - uses: actions/checkout@v2
          - name: Setup Python3.7
            uses: actions/setup-python@v1
            with:
                python-version: 3.7
          - name: Install Dependencies
            run: |
                sudo apt update
                sudo apt install software-properties-common
                sudo add-apt-repository ppa:deadsnakes/ppa
                sudo apt update
                sudo apt-get install python3.7-dev
                sudo apt-get install libsm6 libxext6 libxrender1 libxrender-dev -y --fix-missing
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest
          - name: Checking current directory
            run: | 
               pwd
          - name: checking current directory contents
            run: |
               ls -l
            
          - name: Uploding modules folder
            uses: actions/upload-artifact@v2
            with:
                name: modules
                path: modules/main.py
          - name: Uploding requirements dot txt
            uses: actions/upload-artifact@v2
            with:
                path: requirements.txt
   test:
       runs-on: ubuntu-16.04
       needs: build
       steps:
          - name: Installing dependencies
            run: |
                sudo apt update
                sudo apt install software-properties-common
                sudo add-apt-repository ppa:deadsnakes/ppa
                sudo apt update
                sudo apt-get install python3.7-dev
                sudo apt-get install libsm6 libxext6 libxrender1 libxrender-dev -y --fix-missing
                python -m pip install --upgrade pip
                pip install pytest
          - name: Checking where our home directory is
            run: | 
                 echo $HOME
          - name: Checking our current directory
            run: |
                pwd
          - name: Checking directory currrent dir contents
            run: |
               ls 
          - name: Checking home directory contents
            run: | 
               ls $HOME
          - name: Finding directory of requirements file
            run: | 
               find . -regex '.*requirements.txt$'
          - name: Downloads module folder from build job
            uses: actions/download-artifact@v2 
          - name: Checking if download from build job is successful by running ls command
            run: |
               ls -l          
          - name: Experimenting with running python program from different directory
            run: |
                python modules/main.py
