name: Python package
on: [push]
jobs:
   build:
       runs-on: ubuntu-16.04
       steps:
          - uses: actions/checkout@v2
          - name: Setup Python3.7
            uses: actions/setup-python@v1
            with:
                python-version: 3.7
          - name: Install Dependencies
            run: |
                sudo apt update
                sudo apt install software-properties-common
                sudo add-apt-repository ppa:deadsnakes/ppa
                sudo apt update
                sudo apt-get install python3.7-dev
                sudo apt-get install libsm6 libxext6 libxrender1 libxrender-dev -y --fix-missing
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest
   test:
       runs-on: ubuntu-16.04
       needs: build
       steps:
          - name: Installing dependencies
            run: |
                sudo apt update
                sudo apt install software-properties-common
                sudo add-apt-repository ppa:deadsnakes/ppa
                sudo apt update
                sudo apt-get install python3.7-dev
                sudo apt-get install libsm6 libxext6 libxrender1 libxrender-dev -y --fix-missing
                python -m pip install --upgrade pip
                pip install pytest
          - name: Checking our current directory contents
            run: | 
                ls -l
                pwd
          - name: Experimenting with running python program from different directory
            run: |
                python modules/main.py
